backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/uploads"

editor:
  preview: false # we're going to hide the preview editor

collections:
  - label: "Miscellaneous Pages"
    name: "misc"
    folder: "/src/pages/_netlify_cms_content"
    create: true
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "/src/layouts/netlify_cms.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: Slug, name: slug, widget: string }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "/src/pages/about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
