backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/uploads"

editor:
  preview: false # we're going to hide the preview editor

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, pt]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - label: "Pages"
    name: "pages"
    folder: "/src/pages"
    create: true
    i18n: true
    slug: "{{fields.slug}}"
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "/src/layouts/netlify_cms.astro",
        }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: Slug,
          name: slug,
          widget: string,
          description: "This is the part of the URL which differentiates this page from other pages of the website, e.g. mahayana-in-daily-life. The convention is to use kebab-case.",
          pattern:
            [
              "^[a-z0-9-]+$",
              "The slug must contain only lower case letters, numbers and hyphens",
            ],
          i18n: true,
        }
      - {
          label: "Body",
          name: "body",
          widget: "text",
          required: false,
          i18n: true,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
          i18n: duplicate,
        }
