backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/uploads"

editor:
  preview: false # we're going to hide the preview editor

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - label: "Pages"
    name: "pages"
    folder: "/src/pages"
    create: true
    slug: "{{fields.slug}}"
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "/src/layouts/netlify_cms.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: Slug,
          name: slug,
          widget: string,
          description: "This is the part of the URL which differentiates this page from other pages of the website, e.g. mahayana-in-daily-life. The convention is to use kebab-case.",
          pattern:
            [
              "^[a-z0-9-]+$",
              "The slug must contain only lower case letters, numbers and hyphens",
            ],
        }
      - { label: "Body", name: "body", widget: "text", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
